version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: demo-microservices
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEAFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_EMAIL: -pgadmin4@pgadmin.org
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_DEFAULT_PASSWORD: -admin
#      PGADMIN_CONFIG_SERVER_MODE: 'FALSE'
#    volumes:
#      - ./pgadmin:/var/lib/postgresql/data/
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: